### ISSUE TITLE
JQing a Setter State

### ISSUE THREAD

**Issue by trentis** [direktiv/direktiv#165]
**Is your feature request related to a problem? Please describe.**
JQing a setter state for a string ends up wrapping the variable in quotes. I understand that this intended via JQ but they also offer the flag --raw maybe we could look to be able to use that aswell somehow?

```yaml
id: debug-setter
description: A simple 'no-op' state that returns 'Hello world!'
states:
- id: debug
  type: setter
  variables:
  - key: test
    scope: namespace
    value: jq("this is a string")
```

Saves the variable as '"this is a string"'
