### ISSUE TITLE
Received Events output an error in logs

### ISSUE THREAD

**Issue by trentis** [direktiv/direktiv#290]
can not sync event delays: unmarshal field event: cannot parse uri ref: 

gets outputted whenever we received an event no matter whether or not it is valid

create

```yaml 
start:
  type: event
  event:
    type: greeting
  state: helloworld
states:
- id: helloworld
  type: noop
  transform:
    result: Hello world!
```

run

```yaml
description: A simple 'generateEvent' state that triggers a greeting listener.
states:
- id: generate
  type: generateEvent
  event:
    type: greeting
    source: direktiv
```

to trigger the log line in direktiv flow
