### ISSUE TITLE
Running a workflow with a broken subflow will make instance get stuck on pending

### ISSUE THREAD

**Issue by jalfvort** [direktiv/direktiv#351]
**Describe the bug**
Running a workflow with that calls a subflow action will get stuck on pending if the subflow target workflow does not exist.

**To Reproduce**

This workflow should trigger it
```yaml
functions:
- id: ide
  type: subflow
  workflow: i-dont-exist
states:
- id: getter
  type: action
  action:
    function: ide
```
