### ISSUE TITLE
Variable Setter for base64 does not work correctly

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#449]
**Describe the bug**

If there is state data and I want to store it as binary the setter doesn't work as expected. Assuming the following in the state data:

```
 "zipfile": "UEsFBgAAAAAAAAAAAAAAAAAAAAAAAA=="
```

If I try to store that zip file like this:

```
- id: sstore
  type: setter
  variables: 
    - key: zipper 
      scope: workflow
      value: jq(.zipfile | @base64d)
      mimeType: application/zip
```

It creates a file with the quotes in the content:

```
"PK\u0005\u0006\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
```
