### ISSUE TITLE
JQ in setter state's key

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#472]
**Is your feature request related to a problem? Please describe.**

At the moment I can use jq in the value of the setter state but I can not use it in the key. 

```yaml
- id: storemyvalue
  type: setter
  variables:
    - key: value_for_jq(.name)
      scope: namespace
      value: jq(.name)
```

**Describe the solution you'd like**

It would be good to use the setter in more dynamic way with support for jq in the key.
