### ISSUE TITLE
Start event definition should accept context

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#476]
**Describe the bug**

The docs say that the start event can have a type and context to match. In the UI it throws an error if context is used in the start definition but not in within states. The following should work but the UI throws an error `update workflow: failed to decode start: unknown field "context"`. The context can not be set in any start state (eventsAnd, eventsXor)

```yaml
start:
  type: event
  state: ce
  event:
    type: greetingcloudevent
    context:
      build: asdas
states:    
- id: ce
  type: consumeEvent
  event:
    type: greetingcloudevent
    context:
      build: asdas
  timeout: PT1H
```
