### ISSUE TITLE
jq parsing not working for type:generateEvent->event->type

### ISSUE THREAD

**Issue by wwonigkeit** [direktiv/direktiv#494]
When using the generateEvent state type, unable to use "jq" to create an event type based on the output from a previous state.

See the snippet below:

```yaml
- id: generate-failure-event
    type: generateEvent
    log: 'jq(.error)'
    event:
      type: 'jq(.error.code)'
      source: /login-ssh
      data: ""
      context:
        ipaddress: jq(.ip)
        msg: jq(.error.msg)
```

In the snippet above, I need to create an event based on the error code being returned. But the event “type” is literally created as 'jq(.error.code)'

![Screen Shot 2022-04-01 at 9 34 10 am](https://user-images.githubusercontent.com/11344997/161161278-f7e128aa-3b15-414b-a726-d7c0758da9e8.png)

**Comment by jensg-st** [comment]
Context values can be used for that. If we make that dynamic it can not be traced properly and it can cause bugs which are hard to debug.

**Comment by lianggengdino** [comment]
I want to execute a workflow and pause, and then trigger by event, but just trigger current instance.I know i can definition event type to do it, but if many instances are waiting, i want the instance corresponding to the event notification, not all.
Do u mean i can use `context` to distinguish event, like this?
```
  - id: "wait_host_event"
    type: "consumeEvent"
    event:
      type: "wait_host_event"
      context: 
        instance_id: "jq(.var.instance)"
```
If can`t, what can i do to realize my idea by other way.
