### ISSUE TITLE
foreach needs access to secrets

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#505]
**Is your feature request related to a problem? Please describe.**

Secrets can be passed into an action but if a secret is needed in the array that is impossible.In theory this could be wrapped in a subflow with flow -> subflow as one action -> foreach. But that seems to be an unnecessary overhead. 

Something like the following should be possible:

```yaml
- id: build
  type: foreach
  secrets: ["pwd"]
  array: 
    - name: name1
      mysecret: jq(.secrets.pwd)
    - name: name1
      mysecret: jq(.secrets.pwd)
```
