### ISSUE TITLE
Adding Secrets as file types for actions

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#509]
**Is your feature request related to a problem? Please describe.**

In some cases I would need the secret as a file in the action, e.g. certificate for SSH. At the moment I have to pass it in write it to a file and use it. It could be added as file type to make this process easier:

```
- key: mysecret 
  scope: secret
  as: cert.pem
```

**Comment by jensg-st** [comment]
As an alternative we can maybe something like this:

```yaml
files:
  - data: jq(.secrets.mysecret)
    as: file.pem
```
