### ISSUE TITLE
Git: Event listeners don't work

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#557]
**Describe the bug**

Event listener workflows are not setting up their event listeners if they are getting created via github. Additionally if there are workflows added with e.g. an event start listener these are getting wiped on sync.

To reproduce create the following workflow in git and sync. There is no event listener but if created manually the event listener exists  but getting deleted on next sync. 

```yaml
start:
  type: event
  event: 
    type: gh-event
  state: log
states:
- id: log
  type: noop
  log: jq(.)
```
