### ISSUE TITLE
Cancel does not work if flow is in action

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#575]
**Describe the bug**

Cancel does not work from the UI. If I run the following command with an  invalid container I can not cancel it. 

```yaml
functions:
- id: get
  image: localhost:5000/kubectls
  type: knative-workflow
states:
- id: kubectl 
  type: action
  action:
    function: get
    input: 
      commands:
      - command: ls -la 
```

Subsequent calls of that workflow will not run and the flow engine will crash if the new instance is getting cancelled.
