### ISSUE TITLE
Action timeout finishes the workflow without error

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#578]
**Describe the bug**

If an action has a timeout it should throw a timeout exception but it does not. The following workflow finishes successful although it should throw an error.

```yaml
functions:
- id: kubectl
  image: localhost:5000/kubectl
  type: knative-workflow

states:
- id: deploy-service
  type: action
  timeout: PT1M
  action:
    function: kubectl
    input:
      commands:
      - command: sleep 100000
```
