### ISSUE TITLE
Getter state "as" attribute is getting ignored

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#580]
**Describe the bug**

The `as` parameter is getting ignored. In the following example the variable would be still stored under `var.mykey` instead of `var.mydata`.

```yaml
- id: get
  type: getter
  variables:
  - key: mykey
    scope: namespace
    as: mydata
```

This is only the case if the variable does not exist. The result is that the variable is getting renamed if it exists otherwise not. That causes a problem if there is a switch checking if the value is `null`.
