### ISSUE TITLE
API for async call seems to work but does nothing

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#582]
**Describe the bug**

A flow execution via API without `op=wait` returns with information so the user assumes the workflow kicked of a flow but it did not. Subsequent calls returning the same oid / names. Example call:

```
https://MYSERVER/api/namespaces/test/tree/bash?input.sleep=2
```

```yaml
description: A simple 'action' state that sends a get request
functions:
- id: get
  image: localhost:5000/bash
  type: reusable
- id: sub
  workflow: subflow
  type: subflow
states:
- id: getter 
  type: action
  action:
    function: get
    input: 
      commands:
      - command: sleep jq(.sleep)
  transition: hello
- id: hello
  type: action
  action:
    function: sub
    input: 
      time: |
        js(
          return data["sleep"]
        )
```
