### ISSUE TITLE
functionsHeartbeat does not work if payload is too big

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#603]
**Describe the bug**

The heartbeat function takes all functions within a workflow and does a system sync to identify used/unused workflows. If a workflow has many functions or changes the payload exceeds the size threshold for pg_notify and fails with:

```
db notification failed: pq: payload string too long
```

An easy test is to create a workflow with any functions like the following. The heartbeat method won't work with that flow:

```
functions:
- id: bash
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash1
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash2
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash3
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash4
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash5
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash6
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash7
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash8
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash9
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash10
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash11
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash12
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash13
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash14
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash15
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash16
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash17
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
- id: bash18
  image: localhost:5000/hello:0.0.1-alpha.3
  type: knative-workflow
states:
- id: bash 
  type: action
  action:
    function: bash
    input: 
      name: jens
```
