### ISSUE TITLE
Editor can not  render eventsAnd states

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#625]
**Describe the bug**

The editor can not  render eventsAnd states. It crashes with `TypeError: this.drawflow.drawflow[t] is undefined` and shows a blank screen.

**To Reproduce**

- Create a workflow: 

```
states:
- id: wait-for-tests
  type: eventsAnd
  events:
  - type: event1
  - type: event2
```

- Save and go to editor
