### ISSUE TITLE
cli executes workflow although it has an event start

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#626]
**Describe the bug**

If a workflow has an event start type the cli would start executing it and hang. Execute should not work on event start workflows.

**To Reproduce**

- Create workflow: 

```
functions:
- id: azure
  image: gcr.io/direktiv/apps/azure:test
  type: knative-workflow
start:
  type: event
  state: noop
  event:
    type: io.direktiv.containerapp.create
states:
- id: noop
  type: noop
```
- Execute from CLI: `direktiv-sync exec test.yaml`

**Expected behavior**

The UI returns an error: `execute workflow: cannot manually invoke event-based workflow`. I would expect that from the cli as well.
