### ISSUE TITLE
Foreach hangs on empty arrays

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#633]
**Describe the bug**

If the array value is empty in a foreach, the flow hangs.

**To Reproduce**

- Create a subflow for the foreach action 'print'

```
states:
- id: helloworld
  type: noop
  log: jq(.)
```

- Create flow with a foreach and an empty array

```
functions: 
- id: print
  type: subflow
  workflow: print
states:
- id: setup
  type: noop
  transform:
    data:
      empty: []
  transition: loop

- id: loop
  type: foreach
  array: 'jq([ .data.empty[] | { function: .name } ])'
  action:
    function: print
    input: 'jq(.)'
```

- Running the workflow

A working exmaple would be somethinglike this: 

```
functions: 
- id: print
  type: subflow
  workflow: print
states:
- id: setup
  type: noop
  transform:
    data:
      empty: 
      - name: myname
  transition: loop

- id: loop
  type: foreach
  array: 'jq([ .data.empty[] | { function: .name } ])'
  action:
    function: print
    input: 'jq(.)'
```

**Expected behavior**

Flow proceeds without calling the defined action in the foreach
