### ISSUE TITLE
Invalid subflows causing hanging parent flows

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#654]
**Describe the bug**

If a repository is using git with invalid subflows the calling flow hangs forever and can not be cancelled. In this case there was an invalid "input" section in an action in the subflow. 

```
url: ""
functions:
- type: knative-workflow
  id: http-request
  image: gcr.io/direktiv/apps/http-request:test
states:
- id: state0
  type: action
  action:
    function: http-request
    input:
      true: false
```

The `true: false` is of course wrong and is getting detected if it is not getting synced via git. Git sync is creating this subflow though and the parent hangs if it is calling this subflow. 

I thing the behaviour to not check the workflows on git sync is ok, but it is the general bug if a parent flow calls a invalid subflow which needs to be fixed. 

Additional problem: If i use the CLI to execute the subflow directly `direktiv-sync exec subflow.yaml` it hangs and does nothing. Should we add another issue for that?

**To Reproduce**

Add a namespace with this repository `https://github.com/jensg-st/subflow-bug.git` and execute `flow`
