### ISSUE TITLE
Anti-Affinity rules need rolling update strategy in helm file

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#693]
**Describe the bug**

There is no rolling update strategy in the helm charts but there are anti-affinity rules which breaks the update process. We need to adds something like this:

```
strategy:
  rollingUpdate:
    maxUnavailable: 50%
    maxSurge: 25%
```
