### ISSUE TITLE
GitHub action in marketplace for automated syncs

### ISSUE THREAD

**Issue by wwonigkeit** [direktiv/direktiv#697]
It would be really handy for users to have a GitHub marketplace action they can use to synchronise the repository with a Direktiv mirrored workflow or directory.

Currently I use the following GitHub action to accomplish this on a merge:

```
# This is a basic workflow to help you get started with Actions

name: Push to dev.direktiv.io namespace demo-namespace

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X POST "https://dev.direktiv.io/api/namespaces/demo-namespace/tree?op=sync-mirror&force=true" -H "direktiv-token: ${{ secrets.DIREKTIV_TOKEN }}"
```
