### ISSUE TITLE
how to config subflow

### ISSUE THREAD

**Issue by zzqliwei** [direktiv/direktiv#707]
in Previous version the parent workflow relate to the child workflow by field "id",Workflow does not has filed "id",how the parent workflow relate to the child workflow

**Comment by jensg-st** [comment]
The change was to make the subflow path relative. The following is an example. If you use a value without a starting `/`, the engine looks for a subflow within the directory of the flow getting executed. You can use a starting `/` for absolute paths but `..` notation as well. If it is not starting with `/` it is relative. The docs in getting started need to be updated and we are working on it. 

```
description: A simple 'action' state that sends a get request
functions:
- id: sub
  workflow: ../mysubflow
  type: subflow
states:
- id: getter 
  type: action
  action:
    function: sub
```
