### ISSUE TITLE
Render processes running in parallel in the UI as seperate branches

### ISSUE THREAD

**Issue by wwonigkeit** [direktiv/direktiv#859]
When the following state configuration is used:

```yaml
- id: user-authenticated
    type: parallel
    mode: and
    actions:
      - function: record-user-auth-console-lambda
        input: jq(.userAuthCloudEvent.data)
      - function: record-user-auth-data-sink-lambda
        input: jq(.userAuthCloudEvent.data)
```

Render the parallel states as seperate instances in the UI so that you're able to track the execution of each.

This would look something similar to the `switch` state rending currently used (see screenshot below):

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
